# SOM for CF

SOM code from following repo:

https://github.com/giannisnik/som

https://github.com/Dotori-HJ/SelfOrganizingMap-SOM


In [41]:
import torch
import torch.nn as nn
from torchvision.utils import save_image

import os
import time
import torch
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch.utils.data.dataloader import DataLoader
from torch.utils.data import DataLoader, TensorDataset, SequentialSampler

from sklearn.model_selection import train_test_split

import torch.nn as nn
from torch.autograd import Variable

### Define SOM class

In [42]:
"""
Much of the code is modified from:
- https://codesachin.wordpress.com/2015/11/28/self-organizing-maps-with-googles-tensorflow/
"""

class SOM(nn.Module):
    """
    2-D Self-Organizing Map with Gaussian Neighbourhood function
    and linearly decreasing learning rate.
    """
    def __init__(self, m, n, dim, niter, alpha=None, sigma=None):
        super(SOM, self).__init__()
        self.m = m
        self.n = n
        self.dim = dim
        self.niter = niter
        if alpha is None:
            self.alpha = 0.3
        else:
            self.alpha = float(alpha)
        if sigma is None:
            self.sigma = max(m, n) / 2.0
        else:
            self.sigma = float(sigma)

        self.weights = torch.randn(m*n, dim)
        self.locations = torch.LongTensor(np.array(list(self.neuron_locations())))
        self.pdist = nn.PairwiseDistance(p=2)

    def get_weights(self):
        return self.weights

    def get_locations(self):
        return self.locations

    def neuron_locations(self):
        for i in range(self.m):
            for j in range(self.n):
                yield np.array([i, j])

    def map_vects(self, input_vects):
        to_return = []
        for vect in input_vects:
            min_index = min([i for i in range(len(self.weights))],
                            key=lambda x: np.linalg.norm(vect-self.weights[x]))
            to_return.append(self.locations[min_index])

        return to_return

    def forward(self, x, it):
        dists = self.pdist(torch.stack([x for i in range(self.m*self.n)]), self.weights)
        _, bmu_index = torch.min(dists, 0)
        bmu_loc = self.locations[bmu_index,:]
        bmu_loc = bmu_loc.squeeze()
        
        learning_rate_op = 1.0 - it/self.niter
        alpha_op = self.alpha * learning_rate_op
        sigma_op = self.sigma * learning_rate_op

        bmu_distance_squares = torch.sum(torch.pow(self.locations.float() - torch.stack([bmu_loc for i in range(self.m*self.n)]).float(), 2), 1)
        
        neighbourhood_func = torch.exp(torch.neg(torch.div(bmu_distance_squares, sigma_op**2)))
        
        learning_rate_op = alpha_op * neighbourhood_func

        learning_rate_multiplier = torch.stack([learning_rate_op[i:i+1].repeat(self.dim) for i in range(self.m*self.n)])
        delta = torch.mul(learning_rate_multiplier, (torch.stack([x for i in range(self.m*self.n)]) - self.weights))                                         
        new_weights = torch.add(self.weights, delta)
        self.weights = new_weights
    
    #added
    def get_nearest(self, vect, input_vects, num_neighbors, radius):
        print("enter get_nearest")
        min_index = min([i for i in range(len(self.weights))],
                            key=lambda x: np.linalg.norm(vect-self.weights[x]))
        main_loc = self.locations[min_index] # this is location of vect on grid of SOM
        #print(main_loc)
        #find enough vectors that are close enough (given by num_neighbors & radius)
        print("loop")
        to_return = []
        for v in input_vects:
            min_index = min([i for i in range(len(self.weights))],
                            key=lambda x: np.linalg.norm(v-self.weights[x]))
            v_loc = self.locations[min_index]
            #print(v_loc)
            dist = np.linalg.norm(main_loc-v_loc)
            #print(dist)
            if(dist <= radius):
                to_return.append(v)
            if(len(to_return) >= num_neighbors):
                break 

        if(len(to_return) < num_neighbors): 
            print("Not enough neighbors found. Decrease number of neighbors or increase radius.")
        
        return to_return

Set up directory paths for data, results, models; set up parameters and hyperparameters for the network

In [43]:
#device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device = 'cpu'

# Hyper parameters
DATA_PATH = './data/data_train.csv'
RES_DIR = './results/som/'
MODEL_DIR = './models/som/'


batch_size = 64
total_epoch = 1000
row = 10000
col = 1000
train = False
load = True
n_iter = 100

Get data and set up dataloader (code from official baseline)

In [44]:
#official baseline code

data_pd = pd.read_csv(DATA_PATH)

# Split the dataset into train and test

train_size = 0.9

train_pd, test_pd = train_test_split(data_pd, train_size=train_size, random_state=42)

def extract_users_items_predictions(data_pd):
    users, movies = \
        [np.squeeze(arr) for arr in np.split(data_pd.Id.str.extract('r(\d+)_c(\d+)').values.astype(int) - 1, 2, axis=-1)]
    predictions = data_pd.Prediction.values
    return users, movies, predictions

train_users, train_movies, train_predictions = extract_users_items_predictions(train_pd)

# also create full matrix of observed values
data = np.full((row, col), np.mean(train_pd.Prediction.values))
mask = np.zeros((row, col)) # 0 -> unobserved value, 1->observed value

for user, movie, pred in zip(train_users, train_movies, train_predictions):
    data[user - 1][movie - 1] = pred
    mask[user - 1][movie - 1] = 1


#get test data

test_users, test_movies, test_predictions = extract_users_items_predictions(test_pd)

In [45]:
#official baseline code
# Build Dataloaders
data_torch = torch.tensor(data, device=device).float()
mask_torch = torch.tensor(mask, device=device)

dataloader = DataLoader(
    TensorDataset(data_torch, mask_torch),
    batch_size=batch_size)

In [46]:
print(type(data_torch))

<class 'torch.Tensor'>


### Build model or load it

In [47]:
print('Building Model...')

m=10
n=10

som = SOM(m=m, n=n, dim=1000, niter=n_iter, alpha=None, sigma=None)

if (load and os.path.exists('%s/som.pth' % MODEL_DIR)):
	som.load_state_dict(torch.load('%s/som.pth' % MODEL_DIR))
	print('Model Loaded!')
else:
	print('Create Model!')

som = som.to(device)

Building Model...
Model Loaded!


Training loop 

In [48]:
%%script false --no-raise-error 
som = som.cuda()

In [49]:
if train:
    for iter_no in range(n_iter):
        print("Iter " + str(iter_no))
        #Train with each vector one by one
        for i in range(len(data)):
            #print("Iter " + str(i))
            data_tens = torch.tensor(data[i])
            som(data_tens, iter_no)

        if iter_no % 5 == 0:
            # save
            print("Saving checkpoint")
            torch.save(som.state_dict(), '%s/som.pth' % MODEL_DIR)


In [50]:
%%script false --no-raise-error         # disable cell for now

#Store a centroid grid for easy retrieval later on
centroid_grid = [[] for i in range(m)]
weights = som.get_weights()
locations = som.get_locations()
for i, loc in enumerate(locations):
    centroid_grid[loc[0]].append(weights[i].numpy())
 
#Get output grid
image_grid = centroid_grid

#Map colours to their closest neurons
mapped = som.map_vects(torch.Tensor(data))

#Plot
label_groups = ['1','2','3','4','5','6','7','8','9','10']

plt.imshow(image_grid)
plt.title('SOM')
for i, m in enumerate(mapped):
    plt.text(m[1], m[0], label_groups[i], ha='center', va='center',
             bbox=dict(facecolor='white', alpha=0.5, lw=0))
plt.show()

### Save model

In [51]:
if train:
	torch.save(som.state_dict(), '%s/som.pth' % MODEL_DIR)

### Do predictions

First on test set

In [52]:
#for every user in test set, predict the rating for the respective movie and then compare with actual pred
num_nearest = 10
radius = 1
pred_vals = []

#data_torch = data_torch.cuda()

for u, m in zip(test_users, test_movies):
	print("Current user: " + str(u))
	#get row, is given by user (u-1)
	u_tens = torch.tensor(data[u-1])
	#u_tens = u_tens.cuda()
	ls = som.get_nearest(u_tens, data_torch, num_nearest, radius) #last two params can be changed and finetuned, trial and error

	#ls contains nearest neighbors, max num_nearest, within radius distance
	#if there is warning printed out, max num was not achieved

	idx = m-1
	sum = 0
	tot = len(ls)
	for l in ls:
		sum = sum + l[idx]

	sum = sum - data[u-1][m-1] #sum includes the vector we are trying to predict (since it counts as nearest neighbor), so remove it

	avg = sum/tot #this is prediction
	pred_vals.append(avg)



Current user: 5061
enter get_nearest
tensor([2, 7])
loop
Current user: 9043
enter get_nearest
tensor([2, 7])
loop
Current user: 1735
enter get_nearest
tensor([2, 7])
loop
Current user: 5269
enter get_nearest
tensor([2, 7])
loop
Current user: 6099
enter get_nearest
tensor([2, 7])
loop
Current user: 9927
enter get_nearest
tensor([2, 7])
loop
Current user: 1403
enter get_nearest
tensor([2, 7])
loop
Current user: 3906
enter get_nearest
tensor([2, 7])
loop
Current user: 7716
enter get_nearest
tensor([2, 7])
loop
Current user: 5205
enter get_nearest
tensor([2, 7])
loop
Current user: 2539
enter get_nearest
tensor([2, 7])
loop
Current user: 4643
enter get_nearest
tensor([2, 7])
loop
Current user: 8440
enter get_nearest
tensor([2, 7])
loop
Current user: 2234
enter get_nearest
tensor([2, 7])
loop
Current user: 1745
enter get_nearest
tensor([2, 7])
loop
Current user: 355
enter get_nearest
tensor([2, 7])
loop
Current user: 5032
enter get_nearest
tensor([2, 7])
loop
Current user: 9012
enter get_nea

KeyboardInterrupt: 

In [ ]:
from sklearn.metrics import mean_squared_error

np_test_pred = test_predictions.to_numpy()

rmse = mean_squared_error(pred_vals, np_test_pred, squared=False) #setting to false gives rmse

print("RMSE of predictions and actual ratings of test values: " + str(rmse))